# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Biuld and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies and run tests
      run: npm install
    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Create docker image
       run: docker build -t hsivov/students-app .
     - name: Docker Login
       uses: docker/login-action@v3.1.0
       with:
        # Username used to log against the Docker registry
         username: hsivov
        # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
     - name: Push to Docker Hub
       run: docker push hsivov/students-app
